<?php

/**
 * Group
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    LinkIgniter
 * @subpackage Models
 * @author     YOUR_NAME_HERE <YOUR@NAME.HERE>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Group extends Base_Group
{

}