CREATE TABLE groups (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, name VARCHAR(32) NOT NULL UNIQUE, PRIMARY KEY(id)) ENGINE = INNODB;
CREATE TABLE users (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, username VARCHAR(64) NOT NULL UNIQUE, password VARCHAR(32) NOT NULL, group_id BIGINT UNSIGNED NOT NULL, INDEX group_id_idx (group_id), PRIMARY KEY(id)) ENGINE = INNODB;
ALTER TABLE users ADD CONSTRAINT users_group_id_groups_id FOREIGN KEY (group_id) REFERENCES groups(id);
